for i in range(5):
    print("error: Something failing")